<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>dotnet_prewarm</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsmResolver" Version="6.0.1" />
    <PackageReference Include="AsmResolver.DotNet" Version="6.0.1" />
    <PackageReference Include="AsmResolver.PE" Version="6.0.1" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="dnlib" Version="4.5.0" />
    <PackageReference Include="Iced" Version="1.21.0" />
    <PackageReference Include="ICSharpCode.Decompiler" Version="11.1.0.9782" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.12" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

</Project>
