[package]
name = "prewarm-libs"
version = "0.0.0"
edition = "2021"

[dependencies]
aes-gcm = "0.11.1"
argon2 = "0.6.0"
chacha20poly1305 = "0.11.0"
clap = "4.6.7"
fff-search = "0.11.0"
flate2 = "1.1.10"
goblin = "0.10.7"
iced-x86 = "1.21.0"
jsonwebtoken = "11.1.0"
ldap3 = "0.12.1"
md-5 = "0.11.0"
memmap2 = "0.9.11"
nix = "0.31.3"
nom = "8.0.0"
object = "0.40.0"
p256 = "0.14.0"
pbkdf2 = "0.13.0"
pem = "4.0.0"
pnet = "0.35.0"
quinn = "0.11.12"
rasn = "0.29.0"
rcgen = "0.14.10"
rsa = "0.9.10"
serde = "1.0.229"
thiserror = "2.0.21"
tokio-tungstenite = "0.30.0"
tracing = "0.1.44"
windows-sys = "0.61.2"
x25519-dalek = "3.0.0"
x509-parser = "0.18.1"
zip = "9.0.1"
